--[[
	Localization.fr.lua
		Translations for Dominos

	Spanish
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Dominos-Config', 'esES')
if not L then return end

L.Scale = 'Escala'
L.Opacity = 'Opacidad'
L.FadedOpacity = 'Opacidad al pasar el ratón'
L.Visibility = 'Visibilidad'
L.Spacing = 'Espaciado'
L.Padding = 'Relleno'
L.Layout = 'Dispocición'
L.Columns = 'Columnas'
L.Size = 'Tamaño'
L.Modifiers = 'Modificadores'
L.QuickPaging = 'Paginado Rápido'
L.Help = 'Amigo'
L.Harm = 'Enemigo'
L.Targeting = 'Targeteando'
L.ShowStates = 'Mostrar cuando...'
L.Set = 'Fijar'
L.Save = 'Salvar'
L.Copy = 'Copiar'
L.Delete = 'Borrar'
L.Bar = 'Barra %d'
L.RightClickUnit = 'Clic derecho sobre el objetivo'
L.RCUPlayer = 'Yo'
L.RCUFocus = 'Foco'
L.RCUToT = 'Objetivo del Objetivo'
L.EnterName = 'Entrar nombre'
L.PossessBar = 'Barra de controles'
L.Profiles = 'Perfiles'
L.ProfilesPanelDesc = 'Gestión de los perfiles de Dominos'
L.SelfcastKey = 'Tecla de casteo a uno mismo'
L.QuickMoveKey = 'Tecla de movimiento rápido'
L.ShowMacroText = 'Mostrar el nombre de la macro'
L.ShowBindingText = 'Mostrar los blindeos'
L.ShowEmptyButtons = 'Mostrar los botones vacios'
L.LockActionButtons = 'Bloquear botos de acción'
L.EnterBindingMode = 'Blindeos...'
L.EnterConfigMode = 'Configuración...'
L.ActionBarSettings = 'Ajustes de la bara de acción %d'
L.BarSettings = 'Ajustes de la barra %s'
L.ShowTooltips = 'Mostrar información de los botones'
L.OneBag = 'Una sola bolsa'
L.ShowKeyring = 'Mostrar anillo de llaves'
L.StickyBars = 'Barras autoajustables'
L.ShowMinimapButton = 'Mostrar el botón del minimapa'
L.Advanced = 'Avanzado'
L.LeftToRight = 'Mostrar los botones de izquierda a derecha'
L.TopToBottom = 'Mostrar los botones de arriba a abajo'