--[[
	zhTW (convert from zhCN)
		xuxianhe@gmail.com
		yleaf(yaroot@gmail.com)
]]

local L = LibStub('AceLocale-3.0'):NewLocale('Dominos-Config', 'zhTW')
if not L then return end

L.Scale = '縮放'
L.Opacity = '透明度'
L.FadedOpacity = '遮罩透明度'
L.Visibility = '可見度'
L.Spacing = '間隔'
L.Padding = '填充'
L.Layout = '布局'
L.Columns = '列'
L.Size = '大小'
L.Modifiers = '修飾'
L.QuickPaging = '快速翻頁'
L.Help = '幫助'
L.Harm = '損害'
L.Targeting = '選擇目標時'
L.ShowStates = '顯示狀態'
L.Set = '設置'
L.Save = '保存'
L.Copy = '復制'
L.Delete = '刪除'
L.Bar = '動作條 %d'
L.RightClickUnit = '右鍵點擊'
L.RCUPlayer = '自己'
L.RCUFocus = '監視'
L.RCUToT = '目標的目標'
L.EnterName = '輸入名稱'
L.PossessBar = '心靈控制動作條'
L.Profiles = '配置管理'
L.ProfilesPanelDesc = '允許你管理Dominos插件的配置'
L.SelfcastKey = '自我施法按鍵'
L.QuickMoveKey = '快速移動按鍵'
L.ShowMacroText = '顯示宏名稱'
L.ShowBindingText = '顯示綁定按鍵'
L.ShowEmptyButtons = '顯示空按鈕'
L.LockActionButtons = '鎖定動作條位置'
L.EnterBindingMode = '綁定按鍵...'
L.EnterConfigMode = '進入設置模式'
L.ActionBarSettings = '動作條 %d 設置'
L.BarSettings = '%s 動作條設置'
L.ShowTooltips = '顯示提示'
L.OneBag = '整合背包'
L.ShowKeyring = '顯示鑰匙圈'
L.StickyBars = '粘附動作條'
L.ShowMinimapButton = '顯示小地圖圖標'
